### ISSUE TITLE
Wow

### ISSUE THREAD

**Issue by vincentarelbundock** [larmarange/guide-R#52]
Bonjour Joseph,

Je n'ai pas trouvé de courriel, donc je vous écris ici.

Félicitations pour guide-R. La pédagogie est excellente, le texte clair, et les choix judicieux. J'ai beaucoup aimé les sections sur marginaleffects, dont je suis l'auteur.

Je vais recommander votre site à mes étudiants.

Au plaisir,

Vincent

**Comment by larmarange** [comment]
Un très grand merci pour ce retour. Je suis également un admirateur de `marginaleffects`. Merci pour votre travail.

N'hésitez pas à signaler toute imprécision toute erreur / mauvaise compréhension / mésusage que ce soit sur guide-R ou bien sur l'usage de `marginaleffects` par `broom.helpers`.

Bien cordialement
