### ISSUE TITLE
erreur tbl_summary avec argument by pour certaines variables 

### ISSUE THREAD

**Issue by JeanneGa** [larmarange/guide-R#54]
Bonjour

Je rencontre un souci pour réaliser une analyse bivariée. Lorsque je souhaite utiliser l'argument "by=...", je n'arrive pas à rajouter certaines variables sans avoir le message d'erreur : 
Error in `dplyr::mutate()`:
ℹ In argument: `df_stats = list(...)`.
Caused by error in `dplyr::mutate()`:
ℹ In argument: `stat = map(...)`.
Caused by error:
! glue cannot interpolate functions into strings.
* object 'n' is a function.

Je ne comprends pas comment résoudre le problème 
Merci

**Comment by larmarange** [comment]
Bonjour, sans un exemple complet et reproductive cf. https://thinkr.fr/reprex-ou-comment-demander-de-laide-efficacement/  il m'est difficile de vous répondre.

Impossible de dire s'il s'agit d'une erreur dans votre code ou d'un bug du package

**Comment by larmarange** [comment]
Sans les données, difficile de vous répondre. Y a-t-il des valeurs manquantes ?

Pour vos variables catégorielles, avez-vous essayer de les convertir en facteurs (au lieu d'utiliser un type character) en amont ?

**Comment by JeanneGa** [comment]
Pas de valeurs manquantes pour cette variable. Je vais essayer de les convertir en facteurs, je reviens vers vous si j’ai toujours le problème 
Merci beaucoup pour votre réactivité (et l’ensemble de votre travail !!)

**Comment by JeanneGa** [comment]
ça a fonctionné après conversion en facteurs, merci !
